  INF  Platform/EFI_Binaries/Drivers/sm6150/TzDxe/ScmDxeLA.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/TzDxe/TzDxeLA.inf

  INF  Platform/EFI_Binaries/Drivers/sm6150/FontDxe/FontDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/QcomWDogDxe/QcomWDogDxe.inf
  
  INF  Platform/EFI_Binaries/Drivers/sm6150/ChipInfoDxe/ChipInfoDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/SmemDxe/SmemDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/ULogDxe/ULogDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/NpaDxe/NpaDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/CmdDbDxe/CmdDbDxe.inf 
  INF  Platform/EFI_Binaries/Drivers/sm6150/RpmhDxe/RpmhDxe.inf 
  INF  Platform/EFI_Binaries/Drivers/sm6150/PdcDxe/PdcDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/LimitsDxe/LimitsDxe.inf

  INF  Platform/EFI_Binaries/Drivers/sm6150/DALSYSDxe/DALSYSDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/ClockDxe/ClockDxe.inf

  INF  Platform/EFI_Binaries/Drivers/sm6150/HALIOMMUDxe/HALIOMMUDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/HWIODxe/HWIODxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/GpiDxe/GpiDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/I2CDxe/I2CDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/SPMIDxe/SPMIDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/UFSDxe/UFSDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/SdccDxe/SdccDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/TLMMDxe/TLMMDxe.inf

  INF  Platform/EFI_Binaries/Drivers/sm6150/PlatformInfoDxe/PlatformInfoDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/PmicDxe/PmicDxeLa.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/ChargerExDxe/ChargerExDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/QcomChargerDxe/QcomChargerDxeLA.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/UsbPwrCtrlDxe/UsbPwrCtrlDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/AdcDxe/AdcDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/TsensDxe/TsensDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/DDRInfoDxe/DDRInfoDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/UsbfnDwc3Dxe/UsbfnDwc3Dxe.inf

  INF  Platform/EFI_Binaries/Drivers/sm6150/UsbMsdDxe/UsbMsdDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/UsbDeviceDxe/UsbDeviceDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/UsbConfigDxe/UsbConfigDxe.inf
  
  FILE FREEFORM = 25462CDA-221F-471F-AC1D-25900AF4E326 {
  SECTION RAW = Platform/Xiaomi/sm6150/RawFiles/Panel_shenchao_nt36672a_fhd_video.xml
  SECTION UI = "Panel_shenchao_nt36672a_fhd_video.xml"
}
 FILE FREEFORM = 25462CDA-221F-001F-AC1D-25900AF4E326 {
  SECTION RAW = Platform/Xiaomi/sm6150/RawFiles/Panel_tianma_ft8719_fhd_video.xml
  SECTION UI = "Panel_tianma_ft8719_fhd_video.xml"
} 
 FILE FREEFORM = 25962CDA-221F-001F-AC1D-25900A99E326 {
  SECTION RAW = Platform/Xiaomi/sm6150/RawFiles/Panel_truly_hx83112a_fhd_video.xml
  SECTION UI = "Panel_truly_hx83112a_fhd_video.xml"
} 
 FILE FREEFORM = F0062CDA-221F-001F-AC1D-25900A99E326 {
  SECTION RAW = Platform/Xiaomi/sm6150/RawFiles/Panel_truly_td4328_1080p_cmd.xml
  SECTION UI = "Panel_truly_td4328_1080p_cmd.xml"
} 
 FILE FREEFORM = F0062CDA-221F-001F-AC1D-25900A990000 {
  SECTION RAW = Platform/Xiaomi/sm6150/RawFiles/Panel_truly_td4328_1080p_vid.xml
  SECTION UI = "Panel_truly_td4328_1080p_vid.xml"
} 

  INF  Platform/EFI_Binaries/Drivers/sm6150/ShmBridgeDxe/ShmBridgeDxeLA.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/ResetRuntimeDxe/ResetRuntimeDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/RNGDxe/RngDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/PILDxe/PILDxe.inf
  
  INF  Platform/EFI_Binaries/Drivers/sm6150/QcomBds/QcomBds.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/VerifiedBootDxe/VerifiedBootDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/EnvDxe/EnvDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/ASN1X509Dxe/ASN1X509Dxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/SecRSADxe/SecRSADxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/HashDxe/HashDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/CipherDxe/CipherDxe.inf
